config/routes.rb
Rails.application.routes.draw do
    root 'static_pages#home'

 get '/about', to: 'static_pages#about'
 get '/academics', to: 'static_pages#academics'


get '/reseach', to: 'static_pages#reseach'
  get '/contact', to: 'static_pages#contact'
    get '/admini', to: 'static_pages#admini'
     get '/ske', to: 'static_pages#ske'
      get '/cpe', to: 'static_pages#cpe'
       get '/static', to: 'static_pages#static'
        get '/badit', to: 'static_pages#badit'
                get '/admission', to: 'static_pages#admission'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

protect_from_forgery with: :exception

def home

render html: "hello, world!"

end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end
  def contact
  end

  def home
  end
  def admini
  end
  def admission
  end
  def ske
  end
def badit
end
def cpe
  
end
def static
end


  def reseach
  end  


  def academics
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">

<div class="container">

<li>Copyright © 2017 Department of Computer Engineering. All Rights Reserved  </li>

<ul class="nav navbar-nav navbar-right">

 <li>Computer Engineer Department</li>

<ul>

</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>

<%= csrf_meta_tags %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<!--[if lt IE 9]>

<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">

</script>

<![endif]-->
<style>
</style>

</head>

<body>

<header class="navbar navbar-fixed-top navbar-inverse">

<div class="container">

<%= link_to "Computer Department KU", '#', id: "logo" %>


<nav>

<ul class="nav navbar-nav navbar-right">
  <li><%= link_to "Home Page", root_path %></li>
  <li><%= link_to "About", about_path %></li>
  <li><%= link_to "Administration", admini_path %></li>
  <li><%= link_to "Academic", academics_path %></li>
  <li><%= link_to "Admission", admission_path %></li>
  <li><%= link_to "Research", reseach_path %></li>
  <li><%= link_to "Contact", contact_path %></li>
  
</ul>

</nav>

</div>

</header>

<section>


</section>
<aside>
<%= yield %>
</aside>

</body>
<%= render 'layouts/footer' %>



</html>

app/views/static_pages/Home.html.erb
<h1>CPE Home Page</h1>
<p>Find me in app/views/static_pages/Home.html.erb</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<head>
  <style>
  .content {
    border-style : groove;
    padding-left : 20%;
    padding-right : 20%;
  }

  </style>
</head>
<h1><center>About</center></h1>
<center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/09/DSCF3342-960x350.jpg" width="960" height="350"></center>
<br>
<br>
<div class = "content">
  <p>
    <br>
    OVERVIEW OF OUR DEPARTMENT
    Our Department of Computer Engineering in the Faculty of Engineering, Kasetsart University, was founded on February 3rd, 1989 with the mission to teach, research, develop and service in related areas such that our graduates will meet the market need in Thailand as well as the region.<br></br> Currently, the department is offering degrees in computer engineering, information technology, software engineering and knowledge engineering as follow:

    <ul>
      <li>Bachelor of Engineering in Computer Engineering</li>
      <li>Bachelor of Engineering in Software and Knowledge Engineering</li>
      <li>Master of Science in Information Technology</li>
      <li>Master of Engineering in Computer Engineering</li>
      <li>Doctor of Engineering in Computer Engineering</li>
    </ul>
    In addition to our course offerings, many research units have been founded by faculty members in our department, ranging from development centers and specific research centers to research laboratories. These units are either under the umbrella of the university, the faculty or our department. This leads to the cooperation in research within the university as well as institutions inside and outside the country. Most of our researches have funding from the university, the Royal Thai government, foreign governments and several companies both inside and outside the country.

    Our department encourages our students, staffs, researchers and faculty members to continuously and repeatedly advance the knowledge in the area. We support our members in several ways from participating in academic training, publishing papers in conferences and seeking cooperation with experts in related area worldwide.
  
    Our vision is to continuously take a lead role in education, training and research in computer engineering to make our graduates fully prepared and ready for the rapidly growing industry in Thailand as well as the region.
  </p>
<br>
</div>

<br>
<br>
<br><center><p>SHARE THIS PAGE</p></center><br>

app/views/static_pages/academics.html.erb
<% provide(:title, "About") %>
<head>
  <style>
    .text {
      border-style : none;
      padding-left : 20%;
      padding-right : 20%;
      background-color : #c5d2e8;
    }
    .l {
      background-color : #f2dea2
    }
  </style>
</head>

<body>
  <h1><center>Academics</center></h1>
  <br>
  <br>
  <div class = "text">
    <p class = "l"><br><br></p>
    <br>
    <p >
      <br>
      ภาควิชาฯ ได้เปิดหลักสูตรเพื่อสนองความต้องการของประเทศจำนวน 5 หลักสูตร แบ่งเป็นหลักสูตรระดับปริญญาตรี 1 หลักสูตร หลักสูตรนานาชาติระดับปริญญาตรี 1 หลักสูตร หลักสูตรระดับปริญญาโท 2 หลักสูตร และหลักสูตรระดับปริญญาเอก 1 หลักสูตร คือ

      หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์
      หลักสูตรวิศวกรรมศาสตรบัณฑิตนานาชาติ สาขาวิศวกรรมซอฟต์แวร์และความรู้
      หลักสูตรวิทยาศาสตรมหาบัณฑิต สาขาเทคโนโลยีสารสนเทศ
      หลักสูตรวิศวกรรมศาสตรมหาบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์
      หลักสูตรวิศวกรรมศาสตรดุษฎีบัณฑิต สาขาวิศวกรรมคอมพิวเตอร์
      นอกจากนี้ภาควิชาฯ ยังให้ความร่วมมือในการสอนรายวิชาหลัก รายวิชารอง และรายวิชาเลือก 
      ที่อยู่ในความชำนาญของภาควิชาฯ ดังได้กล่าวข้างต้น ให้แก่หลักสูตรอื่นๆ ทั้งที่เป็นของภาควิชาฯ ภายใต้คณะวิศวกรรมศาสตร์ ภาควิชาต่างคณะ และภาควิชาในต่างวิทยาเขต
      
      <br>
      <br>
    </p>
    <br>
    <p class = "l"><br><br></p>
    
  <br>
  <br>
  <br>SHARE THIS PAGE
  </div>
</body>

app/views/static_pages/admini.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="th">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<head>
  <title> หัวหน้าวิชาภาค </title>
  <style>
    tr, th, td {
      padding-right: 1.625em; border-bottom: 1px solid #EAE7DE;
    }
    #main {
      font-size: 13px;
      line-height: 1.6em;
      margin-top: 20px;
    }

    #main p {
      margin-top: 0;
    }

    #main .column {
      display: inline;
      float: left;
      margin-right: 2.1276%;
    }

    #main .column-narrow {
      width: 23.4042%;
    }

    #main .column-medium {
      width: 48.9361%;
    }

    #main .column-wide {
      width: 74.4680%;
    }

    #main .column-narrow-child {
      width: 31.4685%;
    }

    #main .column-wide-child {
      margin-right: 2.6573%;
      width: 65.7342%;
    }

    #main .column-last {
      margin-right: 0 !important;
    }

    /* Featured Posts */

    .post-content img.aligncenter,
    {
      max-width: 100%;
      width: auto;
      height: auto;
    }

    .full-width .post-content img.aligncenter,
    {
      max-width: 100%;
      width: auto;
      height: auto;
    }

    h1.post-title {
      color: #030B5A;
      font-size: 22px;
      font-weight: bold;
      line-height: 1.5em;
      margin: 0 0 10px;
      font-style: oblique;
    }

    div.cleaner,
    div.clear,
    div.divider {
      margin: 0;
      clear: both;
      font-size: 1px;
      height: 1px;
      line-height: 1px;
    }

    div.divider {
      border-top: solid 1px #e7e7e7;
      clear: none;
      margin: 20px 0;
    }

    .post-content img {
      margin-bottom: 20px;
    }

    .post-content img.alignnone,
    .post-content img.aligncenter,
    .post-content img.alignleft,
    .post-content img.alignright {
      max-width: 100%;
      width: auto;
      height: auto;
    }

    .full-width .post-content img.alignnone,
    .full-width .post-content img.aligncenter,
    .full-width .post-content img.alignleft,
    .full-width .post-content img.alignright {
      max-width: 100%;
      width: auto;
      height: auto;
    }

  </style>
</head>

<body>
  <div class="column column-wide column-last">

    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    <br></br>
    
    <div class="widget">
      <h1 class="post-title">หัวหน้าภาควิชา</h1>

      <div class="divider">&nbsp;</div>

      <div class="post-content">
        <table style="width: 100%;">
          <tbody>
            <tr>
              <td><img class="aligncenter wp-image-1650 size-full" src="https://www.cpe.ku.ac.th/wp-content/uploads/2015/01/Anan-New.jpg" alt="" width="90" height="126" srcset="https://www.cpe.ku.ac.th/wp-content/uploads/2015/01/Anan-New.jpg 180w, https://www.cpe.ku.ac.th/wp-content/uploads/2015/01/Anan-New-39x55.jpg 39w"
                  sizes="(max-width: 90px) 100vw, 90px" /></td>
              <td style="text-align: center;">รศ.ดร.อนันต์ ผลเพิ่ม</td>
              <td style="text-align: center;">พ.ศ. 2557-ปัจจุบัน</td>
            </tr>
            <tr>
              <td><img class="aligncenter size-full wp-image-520" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-8-8-30.jpg" alt="14-KUENG-PHO-01-8-8-30" width="90" height="126" srcset="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-8-8-30.jpg 90w, https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-8-8-30-39x55.jpg 39w"
                  sizes="(max-width: 90px) 100vw, 90px" /></td>
              <td style="text-align: center;">ผศ.ดร. ภุชงค์ อุทโยภาศ</td>
              <td style="text-align: center;">พ.ศ. 2554- 2557</td>
            </tr>
            <tr>
              <td><img class="aligncenter size-full wp-image-519" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-7-7-15.jpg" alt="14-KUENG-PHO-01-7-7-15" width="90" height="126" srcset="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-7-7-15.jpg 90w, https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-7-7-15-39x55.jpg 39w"
                  sizes="(max-width: 90px) 100vw, 90px" /></td>
              <td style="text-align: center;">ผศ.ดร.เขมะฑัต วิภาตะวนิช</td>
              <td style="text-align: center;">พ.ศ. 2549 – 2553</td>
            </tr>
            <tr>
              <td><img class="aligncenter size-full wp-image-557" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-45-45-25.jpg" alt="14-KUENG-PHO-01-45-45-25" width="90" height="126" srcset="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-45-45-25.jpg 90w, https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-45-45-25-39x55.jpg 39w"
                  sizes="(max-width: 90px) 100vw, 90px" /></td>
              <td style="text-align: center;">ผศ.ดร.พีรวัฒน์ วัฒนพงศ์</td>
              <td style="text-align: center;">พ.ศ. 2545 &#8211; 2549</td>
            </tr>
            <tr>
              <td><img class="aligncenter size-full wp-image-514" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-2-2-24.jpg" alt="14-KUENG-PHO-01-2-2-24" width="90" height="126" srcset="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-2-2-24.jpg 90w, https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-2-2-24-39x55.jpg 39w"
                  sizes="(max-width: 90px) 100vw, 90px" /></td>
              <td style="text-align: center;">รศ.ประดนเดช นีละคุปต์</td>
              <td style="text-align: center;">พ.ศ. 2542 &#8211; 2545</td>
            </tr>
            <tr>
              <td><img class="aligncenter size-full wp-image-530" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-18-18-6.jpg" alt="14-KUENG-PHO-01-18-18-6" width="90" height="126" srcset="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-18-18-6.jpg 90w, https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-18-18-6-39x55.jpg 39w"
                  sizes="(max-width: 90px) 100vw, 90px" /></td>
              <td style="text-align: center;">ผศ.ดร.สมนึก คีรีโต</td>
              <td style="text-align: center;">พ.ศ 2539 &#8211; 2542</td>
            </tr>
            <tr>
              <td><img class="aligncenter size-full wp-image-526" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-14-14-13.jpg" alt="14-KUENG-PHO-01-14-14-13" width="90" height="126" srcset="https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-14-14-13.jpg 90w, https://www.cpe.ku.ac.th/wp-content/uploads/2014/10/14-KUENG-PHO-01-14-14-13-39x55.jpg 39w"
                  sizes="(max-width: 90px) 100vw, 90px" /></td>
              <td style="text-align: center;">รศ.ดร.ชัยยงค์ วงศ์ชัยสุวัฒน์</td>
              <td style="text-align: center;">พ.ศ. 2535 &#8211; 2539</td>
            </tr>
            <tr>
              <td><img class="aligncenter wp-image-2466" src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/09/รูปนนทวัฒน์สูท.jpg" alt="" width="90" height="126" srcset="https://www.cpe.ku.ac.th/wp-content/uploads/2014/09/รูปนนทวัฒน์สูท.jpg 180w, https://www.cpe.ku.ac.th/wp-content/uploads/2014/09/รูปนนทวัฒน์สูท-39x55.jpg 39w"
                  sizes="(max-width: 90px) 100vw, 90px" /></td>
              <td style="text-align: center;">อ.นนทวัฒน์ จันทร์เจริญ</td>
              <td style="text-align: center;">พ.ศ.2532 &#8211; 2535</td>
            </tr>
          </tbody>
        </table>

        <div class="cleaner">&nbsp;</div>


      </div>
      <!-- end .post-content -->


      <div class="divider">&nbsp;</div>

      <div class="cleaner">&nbsp;</div>
    </div>
    <!-- end .widget -->

    <div class="cleaner">&nbsp;</div>

  </div>
  <!-- end .column .column-medium -->


  <div class="cleaner">&nbsp;</div>


  </div>
  <!-- end .wrapper -->

  </div>
  <!-- end #main -->
</body>

app/views/static_pages/admission.html.erb
<body>
  <h1>Admission</h1>
  <li><%= link_to "SKE Admission", ske_path %></li>
  <li><%= link_to "CPE Admission", cpe_path %></li>
  <li><%= link_to "Static", static_path %></li>
  <li><%= link_to "Bandit Admission", badit_path %></li>
</body>

app/views/static_pages/contact.html.erb
<p><img style="-webkit-user-select: none;background-position: 0px 0px, 10px 10px;background-size: 20px 20px;background-image:linear-gradient(45deg, #eee 25%, transparent 25%, transparent 75%, #eee 75%, #eee 100%),linear-gradient(45deg, #eee 25%, white 25%, white 75%, #eee 75%, #eee 100%);cursor: zoom-in;" src="https://static1.squarespace.com/static/5550d9d5e4b06b388ebfd48b/t/557f6c2fe4b0bdc1b38471d9/1434414131335/contact.jpg?format=1500w" width="823" height="352">
</p>
<h1> Contact Us <h1>
<p> ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์ มหาวิทยาลัยเกษตรศาสตร์ (วิทยาเขตบางเขน)
<br>เลขที่ 50 ถนนงามวงศ์วาน แขวงลาดยาว
เขตจตุจักร กรุงเทพ ฯ 10900
<br>
<br>โทร. 0-2797-0999 ต่อ 1403-04 1450 <p>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/th_TH/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-page" data-href="https://www.facebook.com/KasetsartCPE/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/KasetsartCPE/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/KasetsartCPE/">Department of Computer Engineering - Kasetsart University</a></blockquote></div>
<br>
<br>
<p><a href="https://www.facebook.com/KasetsartCPE/">Facebook</a>
<br><a href="mailto:cpe@ku.ac.th">E-mail</a> </p>

<br>
<br>
<h8><right><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d17737.74850055379!2d100.57222857019008!3d13.850799434515888!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sth!4v1495699174067" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe></right></h8>

<br>
<br>


<br>SHARE THIS PAGE

app/views/static_pages/home.html.erb
<h1>Welcome to Computer Engineering Department Homepage</h1>
<section>
<div id="fb-root" ></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/th_TH/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-page" data-href="https://www.facebook.com/KasetsartCPE/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/KasetsartCPE/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/KasetsartCPE/">Department of Computer Engineering - Kasetsart University</a></blockquote></div>
</section>

<aside><div class="column column-wide column-wide-parent column-last">

				
				<div class="cleaner">&nbsp;</div>

				<div class="column column-full column-last">
	
					<div class="widget-1 widget-odd widget-0 widget feature-posts" id="wpzoom-feature-posts-5"><ul class="posts posts-archive posts-side">			<li>
				<div class="post-cover"><a href="https://www.cpe.ku.ac.th/?p=3825" title="“KuAcar” คว้าอันดับ2 การแข่งขันรถจำลองไร้คนขับ AMAS MBD 2016"><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2017/02/16837886_10154867331038046_691987547_n.jpg" alt="“KuAcar” คว้าอันดับ2 การแข่งขันรถจำลองไร้คนขับ AMAS MBD 2016" class="Thumbnail thumbnail loop-main " width="210" height="100"></a></div>
				<div class="post-excerpt">
					<h2><a href="https://www.cpe.ku.ac.th/?p=3825" title="Permalink to “KuAcar” คว้าอันดับ2 การแข่งขันรถจำลองไร้คนขับ AMAS MBD 2016" rel="bookmark">“KuAcar” คว้าอันดับ2 การแข่งขันรถจำลองไร้คนขับ AMAS MBD 2016</a></h2>
										<p class="post-meta">
						<span>
							<time datetime="2017-02-22" pubdate="">22nd February 2017</time>							 / <span></span>						</span>
					</p><!-- .post-meta -->
									</div><!-- .post-excerpt -->
			<div class="cleaner">&nbsp;</div>
			</li>
						<li>
				<div class="post-cover"><a href="https://www.cpe.ku.ac.th/?p=3822" title="เปิดรับสมัครผู้สนใจเข้าศึกษาต่อ ระดับปริญญาโทและปริญญาเอก"><img src="http://cpeg.cpe.ku.ac.th/wp-content/uploads/2016/12/11979685575_18b2bf40e9_b-1.png" alt="เปิดรับสมัครผู้สนใจเข้าศึกษาต่อ ระดับปริญญาโทและปริญญาเอก" class="Thumbnail thumbnail loop-main " width="210" height="100"></a></div>
				<div class="post-excerpt">
					<h2><a href="https://www.cpe.ku.ac.th/?p=3822" title="Permalink to เปิดรับสมัครผู้สนใจเข้าศึกษาต่อ ระดับปริญญาโทและปริญญาเอก" rel="bookmark">เปิดรับสมัครผู้สนใจเข้าศึกษาต่อ ระดับปริญญาโทและปริญญาเอก</a></h2>
										<p class="post-meta">
						<span>
							<time datetime="2017-01-23" pubdate="">23rd January 2017</time>							 / <span></span>						</span>
					</p><!-- .post-meta -->
									</div><!-- .post-excerpt -->
			<div class="cleaner">&nbsp;</div>
			</li>
						<li>
				<div class="post-cover"><a href="https://www.cpe.ku.ac.th/?p=3813" title="โครงการเรียนล่วงหน้า ระดับบัณฑิตศึกษา ภาคปลาย ปีการศึกษา 2559"><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2016/12/APP-59-2-study-advance.jpg" alt="โครงการเรียนล่วงหน้า ระดับบัณฑิตศึกษา ภาคปลาย ปีการศึกษา 2559" class="Thumbnail thumbnail loop-main " width="210" height="100"></a></div>
				<div class="post-excerpt">
					<h2><a href="https://www.cpe.ku.ac.th/?p=3813" title="Permalink to โครงการเรียนล่วงหน้า ระดับบัณฑิตศึกษา ภาคปลาย ปีการศึกษา 2559" rel="bookmark">โครงการเรียนล่วงหน้า ระดับบัณฑิตศึกษา ภาคปลาย ปีการศึกษา 2559</a></h2>
										<p class="post-meta">
						<span>
							<time datetime="2016-12-15" pubdate="">15th December 2016</time>							 / <span></span>						</span>
					</p><!-- .post-meta -->
									</div><!-- .post-excerpt -->
			<div class="cleaner">&nbsp;</div>
			</li>
			</ul><div class="cleaner">&nbsp;</div></div>					<div class="cleaner">&nbsp;</div>
	
				</div><!-- end .column .column-wide -->
				
				
				<div class="cleaner">&nbsp;</div>

			</div></aside>

app/views/static_pages/reseach.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="th">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<head>
  <title> งานวิจัย </title>
  <style>
  h1{
    font-family: sans-serif;
    font-style: oblique;
    color: #0A1268;
  }
  p{
    font-family: monospace;
    font-style: normal;
  }
  .post-content{
    padding-left: 20%;
    padding-right: 20%;
    background-color: #c5d2e9;
  }
  </style>
</head>

<body>
  <div class="post-cover post-cover-full single-cover">
    <center><img src="https://www.cpe.ku.ac.th/wp-content/uploads/2014/09/DSCF3353-960x350.jpg" alt="งานวิจัย" class="Thumbnail thumbnail thumb-full " width="960" height="350"></center>
  </div>
  <div class="widget">
    <center><h1 class="post-title">งานวิจัย</h1></center>


    <div class="divider">&nbsp;</div>

    <div class="post-content">
      <br>
      <p>ภาควิชาวิศวกรรมคอมพิวเตอร์ทำการพัฒนาและค้นคว้าวิจัยทางด้านเทคโนโลยีคอมพิวเตอร์ ทั้งด้านฮาร์ดแวร์และซอฟต์แวร์ในสาขาต่าง ๆ เช่น สถาปัตยกรรมคอมพิวเตอร์ เครือข่ายคอมพิวเตอร์และการสื่อสารข้อมูล การประยุกต์ใช้งานไมโครโปรเซสเซอร์ การโปรแกรมระบบ ปัญญาประดิษฐ์
        วิศวกรรมซอฟต์แวร์ การพัฒนาระบบงานคอมพิวเตอร์ ระบบการจัดการฐานข้อมูล และเทคโนโลยีสารสนเทศเพื่อการจัดการ</p>
      <br>
      <div class="cleaner">&nbsp;</div>


    </div>
    <div class="cleaner">&nbsp;</div>
  </div>
</body>